/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tiendaUI;

import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableModel;

import tiendaDataAccess.DataAccessManager;
import tiendaObjetos.Cliente;

/**
 *
 * @author angsaegim
 */
public class TiendaManagementWindow extends javax.swing.JFrame {

    /**
     * Creates new form TiendaAppUI
     */
    //invocamos el método que completa la vista del formulario (se auto-implementa con las acciones que realizamos en tiempo de diseño)      
    public TiendaManagementWindow() throws SQLException {
        initComponents();

        //cargar datos en tabla
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        iniciarPrograma = new javax.swing.JButton();
        iniciarPrograma1 = new javax.swing.JButton();
        iniciarPrograma2 = new javax.swing.JButton();
        iniciarPrograma3 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        iniciarPrograma.setBackground(new java.awt.Color(153, 204, 255));
        iniciarPrograma.setFont(new java.awt.Font("Manjari", 1, 24)); // NOI18N
        iniciarPrograma.setText("Consultar Datos");
        iniciarPrograma.setActionCommand("Consultar");
        iniciarPrograma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciarProgramaActionPerformed(evt);
            }
        });

        iniciarPrograma1.setBackground(new java.awt.Color(153, 204, 255));
        iniciarPrograma1.setText("Nuevo Cliente");
        iniciarPrograma1.setActionCommand("Consultar");
        iniciarPrograma1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciarPrograma1ActionPerformed(evt);
            }
        });

        iniciarPrograma2.setBackground(new java.awt.Color(153, 204, 255));
        iniciarPrograma2.setText("Actualizar Nuevos Clientes");
        iniciarPrograma2.setActionCommand("Consultar");
        iniciarPrograma2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciarPrograma2ActionPerformed(evt);
            }
        });

        iniciarPrograma3.setBackground(new java.awt.Color(153, 204, 255));
        iniciarPrograma3.setText("Borrar clientes");
        iniciarPrograma3.setActionCommand("Consultar");
        iniciarPrograma3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciarPrograma3ActionPerformed(evt);
            }
        });

        jTextField1.setBackground(new java.awt.Color(204, 204, 255));
        jTextField1.setFont(new java.awt.Font("Noto Sans Display ExtraCondensed Medium", 0, 36)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(0, 153, 153));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("TIENDA JARDINERIA");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE)
                    .addComponent(iniciarPrograma2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(iniciarPrograma1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(iniciarPrograma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(iniciarPrograma3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(iniciarPrograma, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(iniciarPrograma1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(iniciarPrograma2)
                .addGap(18, 18, 18)
                .addComponent(iniciarPrograma3)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void iniciarProgramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarProgramaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iniciarProgramaActionPerformed

    private void iniciarPrograma1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarPrograma1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iniciarPrograma1ActionPerformed

    private void iniciarPrograma2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarPrograma2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iniciarPrograma2ActionPerformed

    private void iniciarPrograma3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarPrograma3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iniciarPrograma3ActionPerformed

    private void loadData() throws SQLException {
        //carga de datos en memoria
        List<Cliente> clientes = DataAccessManager.getInstance().loadAllClientes();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton iniciarPrograma;
    private javax.swing.JButton iniciarPrograma1;
    private javax.swing.JButton iniciarPrograma2;
    private javax.swing.JButton iniciarPrograma3;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
